# -*- coding: utf-8 -*-

import streamlit as st
import numpy as np
import pandas as pd
import folium

from folium import plugins

import streamlit_folium
import numpy as np
from streamlit_folium import st_folium
import geopandas as gpd

import branca.colormap as cm

APP_TITLE = 'Energy generated by burning of waste in Sweden'

# st.title(APP_TITLE)
# st.caption('my subtitle')


def display_time_slider(recycling_data):
    year_list= list(recycling_data['year'].unique())
    year_list.sort(reverse= True)
    year= st.radio('Choose a Year', options= year_list)
    # st.header(year)
    return year
def display_measure_filter():
    count=0
    measure=  st.radio ('Measure', ['Total energy produced - Mwh', 'Energy per inhabitant - Mwh'], key='mn')
    # st.write('You select:', 'Measure')
    count += 1
    return measure


def display_map(recycling_data, year, measure):
    recycling_data= recycling_data[recycling_data['year']== year]
    count=0
    # measure = display_measure_filter()
    count+=1
    # st.write(recycling_data['Län'].unique())
    map= folium.Map(location= [63,14], zoom_start=5, tiles= 'CartoDB positron')

    # this is a workaround to make sure the swedish characters are displayed
    import json
    sweden_geojson= gpd.read_file('data/sweden-counties_1680.geojson')
    back_geojson = sweden_geojson.to_json()
    j = json.loads(back_geojson)

    cmap = cm.linear.YlGn_09.to_step(5).scale(recycling_data[measure].min(),
                                               recycling_data[measure].max())
    map.add_child(cmap)
    bins = list(recycling_data[measure].quantile([0,0.05, 0.20,0.3, 0.5,0.7,0.8, 0.90,0.95, 1]))

    choropleth= folium.Choropleth(
        geo_data=j,
        data=recycling_data,
        columns=['Län', measure],
        key_on='feature.properties.NAME_1',
        fill_color="YlGn",
        fill_opacity=0.7,
        line_opacity=0.5,
        legend_name='Energy produced in Mwh',
        bins=bins,
        reset=True)
    choropleth.geojson.add_to(map)
    for feature in choropleth.geojson.data['features']:
        kommun= feature['properties']['NAME_1']
        display1= recycling_data[recycling_data['Län'] == kommun]['Total energy produced - Mwh'].values[0]
        feature['properties']['energy']= str('Energy produced:') + f'{display1:,.2f}' + ' Mwh'
        display2= recycling_data[recycling_data['Län']==kommun]['Energy per inhabitant - Mwh'].values[0]
        feature['properties']['energy per inhabitant']= 'Energy produced per inhabitant:'  + f'{display2:,.2f}' + ' Mwh'

    if measure== 'Energy per inhabitant':
        choropleth.geojson.add_child(folium.features.GeoJsonTooltip(['NAME_1', 'energy per inhabitant'], labels= False))
    if measure== 'Total energy produced - Mwh':
        choropleth.geojson.add_child(folium.features.GeoJsonTooltip(['NAME_1', 'energy'], labels= False))

    st_map= st_folium(map, width=600, height=600)

    # kommun= ''
    # if st.map['last_active_drawing']:
    #     kommun= st_map['last_active_drawing']['properties']['NAME_1']
    # return kommun


def main():
    st.set_page_config(APP_TITLE)
    st.title(APP_TITLE)
    st.caption(
        'Energy recycling, as it is called in Sweden, means the burning of waste in special facilities for the purpose of creating energy, in the form of municipal heating and electricity.')

    #Load Data
    recycling_data = pd.read_csv(
        'data/recycling_data.csv')
    recycling_data['year'] = recycling_data['year'].astype(int)

    col1, col2 = st.columns(2)
    with col1:
        year= display_time_slider(recycling_data)
    with col2:
        measure= display_measure_filter()
    display_map(recycling_data, year, measure)
    # st_map




    # state_name = display_state_filter(df_continental, state_name)
    # measure = display_measure_filter()


# DISPLAY METRICS



if __name__ == "__main__":
    main()
